Update Jenkins_file

diff --git a/Jenkins_file b/Jenkins_file
--- a/Jenkins_file
+++ b/Jenkins_file
@@ -2,13 +2,13 @@ pipeline {
     agent any
     environment {
         SONAR_PROJECT_KEY = 'React.js'
-        GITHUB_REPO = 'https://github.com/DHPLgit/CSAT_Frontend.git'
+        GITHUB_REPO = 'https://github.com/DHPLgit/CSAT_Backend.git'
         SONAR_HOST_URL = 'http://34.213.46.217:9000'
         SONAR_TOKEN = credentials('Sonar_Token') // Replace with the ID of your SonarQube token
         TARGET_SERVER = 'ec2-user@ec2-35-91-75-215.us-west-2.compute.amazonaws.com'
         TARGET_PATH = '/var/www/html/deploy/'
         SSH_KEY_PATH = '/var/jenkins_home/.ssh/id_rsa'
-        ZIP_FILE_NAME = 'csat.zip'
+        ZIP_FILE_NAME = 'csat-be.zip'
     }
 
     stages {
@@ -26,11 +26,11 @@ pipeline {
                         // Ensure the src folder exists
                         echo "Archiving source folder into ${ZIP_FILE_NAME}..."
                         sh """
-                            if [ ! -d csat ]; then
-                                echo "Error: Directory 'csat/' not found!" >&2
+                            if [ ! -d csat-be ]; then
+                                echo "Error: Directory 'csat-be/' not found!" >&2
                                 exit 1
                             fi
-                            zip -r ${ZIP_FILE_NAME} csat/
+                            zip -r ${ZIP_FILE_NAME} csat-be/
                         """
 
                         echo "Transferring ${ZIP_FILE_NAME} to the target server..."
